// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gasbrtqkyjxhoycimhgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdhc2JydHFreWp4aG95Y2ltaGdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjQyMzgsImV4cCI6MjA2ODYwMDIzOH0.M18tBVxAOODe0zzx_iEsPcel96JaOriDNf8R_cICoIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});